name: Release
run-name: Release ${{ github.ref_name }}
on:
  push:
    tags:
      - v*
  workflow_dispatch:
jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
    env:
      RELEASE_ZIP_FILENAME: ${{ github.event.repository.name }}-${{ github.ref_name }}-win-x64.zip
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up MSVC environment
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756
      - name: Build
        run: make build
      - name: Create release ZIP file
        run: |
          Copy-Item LICENSE,COPYRIGHT out
          Rename-Item out ${{ github.event.repository.name }}
          Compress-Archive ${{ github.event.repository.name }} ${{ env.RELEASE_ZIP_FILENAME }}
      - name: Release on GitHub
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          files: ${{ env.RELEASE_ZIP_FILENAME }}
